#title:             Keeping up With Java - KUWJ
#email:             your-email@example.com
description:       Um Blog para se mantém informado com o mundo Java.
author:            SouJava
#baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://kuwj.github.io"

# Social Profiles
twitter_username:  soujava
github_username:   SouJava
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
